apiVersion: batch/v1
kind: Job
metadata:
  name: load-data-job
spec:
  template:
    spec:
      containers:
        - name: load-data
          image: shazam007/node-user-api
          volumeMounts:
            - name: config-volume
              mountPath: /app/data.csv
              subPath: data.csv
      restartPolicy: OnFailure
      volumes:
        - name: config-volume
          configMap:
            name: node-user-api-data
